Part 2
Heartzian/PFMCPP_Project3 pull request #2
Opened 2022-02-07 05:19 UTC by Heartzian

2022-02-07 05:45 UTC, matkatmusic requested changes
Your code produces a lot of warnings when it is compiled and executed.
Please fix the warnings and re-request a review.

2022-02-08 12:20 UTC, Heartzian reviewed
Checked!

2022-02-08 19:15 UTC, matkatmusic requested changes

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +                    (dinnerProds * dProdsPrice);
remove the `\`.  It is not necessary and just adds visual confusion to the code.
Semicolons indicate the end of a statement in C++, not newlines.
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    numPeopleWorkingAtStore--;
use pre-increment/decrement, not post-increment/decrement.
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +        float weekStudyTime(int research = 28, int teaching = 16);
Add a verb to this function name.  `computeWeekStudyTime` is a good choice
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    return canUseAtOffice = true;
Do not write code like this.
What value are you returning?
it is impossible to reason which value is being returned.
Separate the assignment `= true` from the value being returned.
```
canUseAtOffice = true;
return .......
```
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    return canSaveInfo = true;
Do not write code like this.
What value are you returning?
it is impossible to reason which value is being returned.
Separate the assignment `= true` from the value being returned.
```
canSaveInfo = true;
return .......
```
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    return canPlayGames = true;
Do not write code like this.
What value are you returning?
it is impossible to reason which value is being returned.
Separate the assignment `= true` from the value being returned.
```
canPlayGames = true;
return .......
```
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    return canTrainAI = true;
Do not write code like this.
What value are you returning?
it is impossible to reason which value is being returned.
Separate the assignment `= true` from the value being returned.
```
canTrainAI = true;
return .......
```
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    return teachedClasses;
Skip the temporary variable.
`return calculus + programming + cad;`
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +float University::teachStudents(Professor)
What is the point of declaring a function parameter if you're not going to use it?
- [ ] revise: either use the function parameter or remove the function parameter

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    return x;
Don't pass in an instance of the `Oscillator` class into an Oscillator member function!
If you're trying to use `waveformShape`, which is a member variable of the `Oscillator` instance being used when this function is called, just use it directly inside the function.   
```
if( waveformShape == "Square" )
    x = 0.5 * frequency;

return x;
```
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    while (anyKeyPressed == true);
Loops have not been covered yet. 
write something else
This function implementation easy creates an infinite loop if you call this function with `anyKeyPressed` set to `true`.
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
>  {
This class represents ONE filter, not multiple filters
Name it that way
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +    LowShelf.gain=-12;
Do not pass in an instance of `Filter` into a `Filter` member function
You can use the member variables of the calling instance directly inside the member function. 
- [ ] revise

2022-02-08 19:15 UTC, matkatmusic commented on main.cpp
> +}
Do not pass a `Reverb` into a `Reverb` member function
- [ ] revise

2022-02-09 20:45 UTC, matkatmusic approved these changes

2022-02-09 20:45 UTC, merged